version: '3.1'

services:
  gameday-db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - spring-cloud-network
    environment:
      POSTGRES_PASSWORD: password

  gameday-server:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - spring-cloud-network
    depends_on:
      - gameday-db

networks:
    spring-cloud-network:
        driver: bridge