version: '3.1'

services:
  gameday-db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    networks:
      - spring-cloud-network
    environment:
      POSTGRES_PASSWORD: password
      
networks:
    spring-cloud-network:
        driver: bridge