version: '3.1'

services:
  gameday-db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password

  gameday-server:
    container_name: gameday-server
    build: ./
    image: gameday-server:latest
    ports:
      - 8080:8080
    depends_on:
      - gameday-db